# -*- coding: utf-8 -*-
"""music upload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uts7QTKqZqnET_2MG4tQsM59E0u5Mmm0
"""

import pandas as pd
import matplotlib.pyplot as plt
from firebase_admin import credentials, firestore, initialize_app
import time

cred = credentials.Certificate("/content/data-analysis-6df39-firebase-adminsdk-gzv79-45763a684f.json")
initialize_app(cred,{'databaseURL':'https://data-analysis-6df39.firebaseio.com/'})

db = firestore.client()
doc_ref = db.collection('training')

df = pd.read_csv('/content/top 100 streamed songs.csv')
tmp = df.to_dict(orient='records')
for rec in tmp:
  print(rec)
  doc_ref.add(rec)
  print('Entry Added')
  time.sleep(1)

